[BankList]
BankList=Drum, Melodic, Chords

[Banks]
Chords=Chords_EP-MK1_Rhodes
Drum=VeeOneDrum, Virtuosity, Urban
Melodic=EP-MK1_Rhodes

[PresetList]
PresetList=@Invalid()

[Presets]
Chords_EP-MK1_Rhodes=Chords_EP-MK1_Rhodes.drumkv1
EP-MK1_Rhodes=EP-MK1_Rhodes.drumkv1
Urban=Urban.drumkv1
VeeOneDrum=VeeOneDrum.drumkv1
Virtuosity=Virtuosity.drumkv1
