[BankList]
BankList=Drum, Melodic, Chords

[Banks]
Chords=Chords_EP-MK1_Rhodes
Drum=VeeOneDrum, Bright_VeeOneDrum, Virtuosity, Urban, Bright_Urban
Melodic=EP-MK1_Rhodes, Orshortra

[Presets]
Bright_Urban=Bright_Urban.drumkv1
Bright_VeeOneDrum=Bright_VeeOneDrum.drumkv1
Chords_EP-MK1_Rhodes=Chords_EP-MK1_Rhodes.drumkv1
EP-MK1_Rhodes=EP-MK1_Rhodes.drumkv1
Orshortra=Orshortra.drumkv1
Urban=Urban.drumkv1
VeeOneDrum=VeeOneDrum.drumkv1
Virtuosity=Virtuosity.drumkv1
